stages:
  get_n_save_data:
    cmd: python src/stage_01_load_n_save_data.py
    deps:
    - src/stage_01_load_n_save_data.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - artifacts/raw_local_dir/data.csv

  data_preprocessing:
    cmd: python src/stage_02_data_preprocessing.py
    deps:
    - src/stage_02_data_preprocessing.py
    - src/utils/common.py
    - artifacts/raw_local_dir/data.csv
    - configs/config.yaml
    params:
      - base.n_jobs
      - imputer.max_iter
      - imputer.tol
      - imputer.random_state
      - imputer.imputation_order
      - imputer.verbose
    outs:
    - artifacts/raw_local_dir/furnished_data.csv

  split_data:
    cmd: python src/stage_03_train_test_split.py
    deps:
    - src/stage_02_data_preprocessing.py
    - src/utils/common.py
    - artifacts/raw_local_dir/furnished_data.csv
    - configs/config.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
    - artifacts/split_data_dir/X_train.csv
    - artifacts/split_data_dir/X_test.csv
    - artifacts/split_data_dir/y_train.csv
    - artifacts/split_data_dir/y_test.csv
  train:
    cmd: python src/stage_04_model_training.py
    deps:
    - src/stage_04_model_training.py
    - src/utils/common.py
    - artifacts/split_data_dir/X_train.csv
    - artifacts/split_data_dir/X_test.csv
    - artifacts/split_data_dir/y_train.csv
    - artifacts/split_data_dir/y_test.csv
    params:
      - model_params.Lightgbm.boosting_type
      - model_params.Lightgbm.objective
      - model_params.Lightgbm.n_estimators
      - base.random_state
      - base.n_jobs      
    outs:
    - artifacts/model_dir/model.pkl
  evaluate:
    cmd: python src/stage_05_evaluate.py
    deps:
    - src/stage_05_evaluate.py
    - src/utils/common.py
    - artifacts/split_data_dir/X_test.csv
    - artifacts/split_data_dir/y_test.csv
    - artifacts/model_dir/model.pkl
    - params.yaml
    - configs/config.yaml     
    metrics:
      - scores.json:
          cache: false
