# add stages here 
stages:
  get_n_save_data:
    cmd: python src/stage_01_load_n_save_data.py
    deps:
    - src/stage_01_load_n_save_data.py
    - src/utils/common.py
    outs:
    - artifacts/raw_local_dir/data.csv
  data_preprocessing:
    cmd: python src/stage_01_load_n_save_data.py
    deps:
    - src/stage_01_load_n_save_data.py
    - src/utils/common.py
    outs:
    - artifacts/raw_local_dir/data.csv

