# This contains params to be used by the stages to train or predict

dataset:
  name: product

base:
  random_state: 11
  test_size: 0.2
  n_jobs: -1

imputer:
  max_iter: 10
  tol: 1e-10
  random_state: 0
  imputation_order: roman
  verbose: 2


model_params:
  Lightgbm:
    boosting_type: goss
    objective: binary
    n_estimators: 200

