# It contains all the configs required in the project

data_source: https://akashbws8158894669.blob.core.windows.net/azureml-blobstore-aaaa0ae0-13b1-4df4-ae9b-fa32525b3243/UI/09-19-2022_010328_UTC/train_data_bo.csv


artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_LOCAL_DIR: raw_local_dir
  RAW_LOCAL_FILE: data.csv 
  PREP_FILE: furnished_data.csv
  SPLIT_DATA_DIR: split_data_dir
  X_TRAIN: X_train.csv
  X_TEST: X_test.csv
  Y_TRAIN: y_train.csv
  Y_TEST: y_test.csv
  TRAINED_MODEL_DIR: model_dir
  TRAINED_MODEL_NAME: model.pkl
  
scores: scores.json
azure:
  subscription_id: 2ff60c86-4824-4a6a-bb33-beb7c5b60b23
  resource_group: akashb-rg
  workspace_name: akashb-ws