# It contains all the configs required in the project



artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_LOCAL_DIR: raw_local_dir
  RAW_LOCAL_FILE: data.csv 
  PREP_FILE: furnished_data.csv
  SPLIT_DATA_DIR: split_data_dir
  X_TRAIN: X_train.csv
  X_TEST: X_test.csv
  Y_TRAIN: y_train.csv
  Y_TEST: y_test.csv
  TRAINED_MODEL_DIR: model
  TRAINED_MODEL_NAME: model.pkl
  
azure:
  subscription_id: 2ff60c86-4824-4a6a-bb33-beb7c5b60b23
  resource_group: akashb-rg
  workspace_name: akashb-ws